terminate called after throwing an instance of 'std::runtime_error'
  what():  /Users/tmwilde/Desktop/MILO/src/interfaces/userInterface.hpp:177:

Throw number = 1

Throw test that evaluated to true: true

Error: the input.xml needs to contain either a Discretization sublist or a path to a Discretization settings file!
[s998638:50011] *** Process received signal ***
[s998638:50011] Signal: Abort trap: 6 (6)
[s998638:50011] Signal code:  (0)
[s998638:50011] *** End of error message ***
terminate called after throwing an instance of 'std::runtime_error'
  what():  /Users/tmwilde/Desktop/MILO/src/interfaces/userInterface.hpp:177:

Throw number = 1

Throw test that evaluated to true: true

Error: the input.xml needs to contain either a Discretization sublist or a path to a Discretization settings file!
[s998638:50012] *** Process received signal ***
[s998638:50012] Signal: Abort trap: 6 (6)
[s998638:50012] Signal code:  (0)
[s998638:50012] *** End of error message ***
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 1 with PID 0 on node s998638 exited on signal 6 (Abort trap: 6).
--------------------------------------------------------------------------
